# Generated by Django 4.1.2 on 2022-12-08 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='Destination',
        ),
    ]
